"""Add datetime to  SensorData table

Revision ID: b42e786da2f7
Revises: c5b3afc0dab5
Create Date: 2024-07-23 17:46:46.611462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b42e786da2f7'
down_revision = 'c5b3afc0dab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordata', 'time')
    # ### end Alembic commands ###
