"""Add SensorHealth table

Revision ID: c5b3afc0dab5
Revises: c626da033038
Create Date: 2024-07-23 17:25:47.575072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5b3afc0dab5'
down_revision = 'c626da033038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorhealth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('dcp', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('fault', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensorhealth')
    # ### end Alembic commands ###
