"""Add SensorData table

Revision ID: c626da033038
Revises: f1af976a85b5
Create Date: 2024-07-23 16:59:45.824016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c626da033038'
down_revision = 'f1af976a85b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('class_type', sa.Enum('car', 'motorcycle', 'pedestrian', 'bicycle', name='sensorclass'), nullable=False),
    sa.Column('approach', sa.Enum('NB', 'SB', 'WB', 'EB', name='approach'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensordata')
    # ### end Alembic commands ###
